"use strict";
exports.__esModule = true;
var aluno_1 = require("./aluno");
var exe1_1 = require("./exe1");
var lista = new exe1_1.ListaLigada();
lista.adicionar(new aluno_1.Aluno('Ronaldo', 28));
lista.adicionar(new aluno_1.Aluno('Carol', 40));
lista.adicionar(new aluno_1.Aluno('Betty', 30));
lista.adicionaNoComeco(new aluno_1.Aluno('Marina', 10));
console.log(lista.toString());
console.log(lista.tamanho());
lista.remove(2);
console.log(lista.toString());
lista.removeDoComeco();
console.log(lista.pega(1));
lista.removeDoFim();
lista.contem(new aluno_1.Aluno('Betty', 1));
console.log(lista.toString());
